import os

def load_pll_regs(filename="lmk04208_registers.tcs"):
    """
    Load the register values in the .tcs file generated by TICSPRO software.
    """
    fullpath = os.path.join(os.path.dirname(__file__), filename)
    regs = []
    with open(fullpath, 'r') as f:
        for line in f.readlines():
            if line.startswith('NAME'):
                key, val = line.split('=')
                if val[0] != 'R':
                    raise RuntimeError(f'Unknown register field in line {line}') 
                val = val.split()[0] # drop comment
                reg = int(val[1:])
            if line.startswith('VALUE'):
                key,val = line.split('=')
                regs.append((reg, int(val)))
    return regs

